name: GitHub Metrics

on:
  schedule: [{cron: "0 12 * * *"}]  # Atualiza todos os dias às 9h (GMT-3)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          user: GabrielPrad
          token: ${{ secrets.METRICS_TOKEN }}

          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_ignored: >-
            dockerfile, makefile
          plugin_languages_limit: 5
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_lines: yes
          plugin_notable: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
